### ISSUE TITLE
Incorrect parentheses in L204

### ISSUE THREAD

**Issue by raivivek** [PriceLab/SIGDA#1]
Hi @maxbox51 

Out of curiosity I was trying to run SIGDA on a toy dataset. Looks like there's a bug in line 204 due to wrong placement of parentheses?

https://github.com/PriceLab/SIGDA/blob/master/sigda.R#L204

**Comment by maxbox63** [comment]
Thanks Vivek. I of course noticed and fixed it long ago, but I have so many versions running around on my machines it never got pushed. This code base is a radically simplified version of my original code, which I developed for huge matrices; I haven't tested how large a dataset this can be used on.

**Comment by raivivek** [comment]
Oh that's a bummer. I was hoping to test it on a rather large matrix.. but wasn't so sure about it. Do you plan to release original code sometime or that's gonna come out later with some other publication?

**Comment by maxbox63** [comment]
What do you call a rather large matrix? My large matrices were 2,500 x 500,000, and I used sparse matrix methods to be able to handle that. If the matrix is dense, that doesn't help.

If on the other hand your matrix is fully dense and 10,000 by 10,000, this code should probably handle it fine.

**Comment by raivivek** [comment]
It's a sparse matrix (~ 90% empty cells) something to the order of 5000 x
100000 or so.
